Rails.application.routes.draw do
  # TODO: incapsulation???
  resources :users do
    resources :courses, only: [:create, :destroy]
  end
  resources :courses, excepct: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'pages#home'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)
  get 'add_course/:user_id/:course_id', to: 'registrations#add_course'
  get 'drop_course/:user_id/:course_id', to: 'registrations#drop_course'

end
